name: Setup the dev server project

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: "~/Repos/Tashgheel-Website_Api/"
      
    steps:
      - name: Restart the server project
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_HOST_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            PORT=5532
            PIDS=$(lsof -ti:$PORT)
            if [ -z "$PIDS" ]; then
            echo "No processes are using port $PORT."
            else
              for PID in $PIDS; do
                echo "Killing process $PID..."
              done
            fi
            kill -9 $PIDS

            cd ${{ env.PROJECT_PATH }}
            git pull
            nohup dotnet run --urls "http://${{ vars.SERVER_HOST_ADDRESS }}:5532" > /dev/null 2>&1 &
